"""Add unique constraint for campaign phone duplicates

Revision ID: 290d11dba14d
Revises: be43f8bb42d0
Create Date: 2025-06-25 22:03:53.377167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '290d11dba14d'
down_revision: Union[str, None] = 'be43f8bb42d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_campaign_phone', 'message', ['campaign_id', 'phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_campaign_phone', 'message', type_='unique')
    # ### end Alembic commands ###
