"""Add user metrics table

Revision ID: 4669eb7a8878
Revises: a5a3f106534b
Create Date: 2025-05-01 22:14:21.434189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4669eb7a8878'
down_revision: Union[str, None] = 'a5a3f106534b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usermetrics',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('messages_delivered', sa.Integer(), nullable=False),
    sa.Column('messages_failed', sa.Integer(), nullable=False),
    sa.Column('messages_scheduled', sa.Integer(), nullable=False),
    sa.Column('campaigns_created', sa.Integer(), nullable=False),
    sa.Column('campaigns_completed', sa.Integer(), nullable=False),
    sa.Column('campaigns_active', sa.Integer(), nullable=False),
    sa.Column('templates_created', sa.Integer(), nullable=False),
    sa.Column('templates_used', sa.Integer(), nullable=False),
    sa.Column('quota_total', sa.Integer(), nullable=False),
    sa.Column('quota_used', sa.Integer(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uix_user_date')
    )
    op.create_index(op.f('ix_usermetrics_date'), 'usermetrics', ['date'], unique=False)
    op.create_index(op.f('ix_usermetrics_id'), 'usermetrics', ['id'], unique=False)
    op.create_index(op.f('ix_usermetrics_user_id'), 'usermetrics', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usermetrics_user_id'), table_name='usermetrics')
    op.drop_index(op.f('ix_usermetrics_id'), table_name='usermetrics')
    op.drop_index(op.f('ix_usermetrics_date'), table_name='usermetrics')
    op.drop_table('usermetrics')
    # ### end Alembic commands ###
