"""Add campaign personalization and import pipeline

Revision ID: be43f8bb42d0
Revises: 4669eb7a8878
Create Date: 2025-06-22 18:37:25.178324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be43f8bb42d0'
down_revision: Union[str, None] = '4669eb7a8878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('importjob',
    sa.Column('status', sa.Enum('PROCESSING', 'SUCCESS', 'FAILED', 'CANCELLED', name='importstatus'), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_importjob_id'), 'importjob', ['id'], unique=False)
    op.create_index(op.f('ix_importjob_owner_id'), 'importjob', ['owner_id'], unique=False)
    op.create_index(op.f('ix_importjob_sha256'), 'importjob', ['sha256'], unique=False)
    op.create_index(op.f('ix_importjob_status'), 'importjob', ['status'], unique=False)
    op.create_table('contact',
    sa.Column('import_id', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('csv_row_number', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['importjob.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'phone', name='uix_import_phone')
    )
    op.create_index(op.f('ix_contact_id'), 'contact', ['id'], unique=False)
    op.create_index(op.f('ix_contact_import_id'), 'contact', ['import_id'], unique=False)
    op.create_index(op.f('ix_contact_phone'), 'contact', ['phone'], unique=False)
    op.add_column('campaign', sa.Column('message_content', sa.Text(), nullable=True))
    op.add_column('campaign', sa.Column('template_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_campaign_template_id'), 'campaign', ['template_id'], unique=False)
    op.create_foreign_key(None, 'campaign', 'messagetemplate', ['template_id'], ['id'])
    op.add_column('message', sa.Column('variables', sa.JSON(), nullable=True))
    op.add_column('message', sa.Column('import_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_message_import_id'), 'message', ['import_id'], unique=False)
    op.create_foreign_key(None, 'message', 'importjob', ['import_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_index(op.f('ix_message_import_id'), table_name='message')
    op.drop_column('message', 'import_id')
    op.drop_column('message', 'variables')
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    op.drop_index(op.f('ix_campaign_template_id'), table_name='campaign')
    op.drop_column('campaign', 'template_id')
    op.drop_column('campaign', 'message_content')
    op.drop_index(op.f('ix_contact_phone'), table_name='contact')
    op.drop_index(op.f('ix_contact_import_id'), table_name='contact')
    op.drop_index(op.f('ix_contact_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_importjob_status'), table_name='importjob')
    op.drop_index(op.f('ix_importjob_sha256'), table_name='importjob')
    op.drop_index(op.f('ix_importjob_owner_id'), table_name='importjob')
    op.drop_index(op.f('ix_importjob_id'), table_name='importjob')
    op.drop_table('importjob')
    # ### end Alembic commands ###
