"""Fresh database schema with all models

Revision ID: cec7a3b1e429
Revises: 290d11dba14d
Create Date: 2025-06-25 22:08:47.772203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec7a3b1e429'
down_revision: Union[str, None] = '290d11dba14d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('webhookevent',
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('gateway_message_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhookevent_event_type'), 'webhookevent', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhookevent_gateway_message_id'), 'webhookevent', ['gateway_message_id'], unique=False)
    op.create_index(op.f('ix_webhookevent_id'), 'webhookevent', ['id'], unique=False)
    op.create_index(op.f('ix_webhookevent_message_id'), 'webhookevent', ['message_id'], unique=False)
    op.create_index(op.f('ix_webhookevent_phone_number'), 'webhookevent', ['phone_number'], unique=False)
    op.create_table('apikey',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apikey_id'), 'apikey', ['id'], unique=False)
    op.create_index(op.f('ix_apikey_key'), 'apikey', ['key'], unique=True)
    op.create_table('importjob',
    sa.Column('status', sa.Enum('PROCESSING', 'SUCCESS', 'FAILED', 'CANCELLED', name='importstatus'), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_importjob_id'), 'importjob', ['id'], unique=False)
    op.create_index(op.f('ix_importjob_owner_id'), 'importjob', ['owner_id'], unique=False)
    op.create_index(op.f('ix_importjob_sha256'), 'importjob', ['sha256'], unique=False)
    op.create_index(op.f('ix_importjob_status'), 'importjob', ['status'], unique=False)
    op.create_table('messagebatch',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('successful', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messagebatch_id'), 'messagebatch', ['id'], unique=False)
    op.create_index(op.f('ix_messagebatch_status'), 'messagebatch', ['status'], unique=False)
    op.create_index(op.f('ix_messagebatch_user_id'), 'messagebatch', ['user_id'], unique=False)
    op.create_table('messagetemplate',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messagetemplate_id'), 'messagetemplate', ['id'], unique=False)
    op.create_index(op.f('ix_messagetemplate_name'), 'messagetemplate', ['name'], unique=False)
    op.create_index(op.f('ix_messagetemplate_user_id'), 'messagetemplate', ['user_id'], unique=False)
    op.create_table('usermetrics',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('messages_delivered', sa.Integer(), nullable=False),
    sa.Column('messages_failed', sa.Integer(), nullable=False),
    sa.Column('messages_scheduled', sa.Integer(), nullable=False),
    sa.Column('campaigns_created', sa.Integer(), nullable=False),
    sa.Column('campaigns_completed', sa.Integer(), nullable=False),
    sa.Column('campaigns_active', sa.Integer(), nullable=False),
    sa.Column('templates_created', sa.Integer(), nullable=False),
    sa.Column('templates_used', sa.Integer(), nullable=False),
    sa.Column('quota_total', sa.Integer(), nullable=False),
    sa.Column('quota_used', sa.Integer(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uix_user_date')
    )
    op.create_index(op.f('ix_usermetrics_date'), 'usermetrics', ['date'], unique=False)
    op.create_index(op.f('ix_usermetrics_id'), 'usermetrics', ['id'], unique=False)
    op.create_index(op.f('ix_usermetrics_user_id'), 'usermetrics', ['user_id'], unique=False)
    op.create_table('webhook',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('event_types', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('secret_key', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('gateway_webhook_id', sa.String(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_id'), 'webhook', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_user_id'), 'webhook', ['user_id'], unique=False)
    op.create_table('campaign',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('delivered_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('scheduled_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['messagetemplate.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_id'), 'campaign', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_name'), 'campaign', ['name'], unique=False)
    op.create_index(op.f('ix_campaign_scheduled_start_at'), 'campaign', ['scheduled_start_at'], unique=False)
    op.create_index(op.f('ix_campaign_status'), 'campaign', ['status'], unique=False)
    op.create_index(op.f('ix_campaign_template_id'), 'campaign', ['template_id'], unique=False)
    op.create_index(op.f('ix_campaign_user_id'), 'campaign', ['user_id'], unique=False)
    op.create_table('contact',
    sa.Column('import_id', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('csv_row_number', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['importjob.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'phone', name='uix_import_phone')
    )
    op.create_index(op.f('ix_contact_id'), 'contact', ['id'], unique=False)
    op.create_index(op.f('ix_contact_import_id'), 'contact', ['import_id'], unique=False)
    op.create_index(op.f('ix_contact_phone'), 'contact', ['phone'], unique=False)
    op.create_table('message',
    sa.Column('custom_id', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('gateway_message_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('import_id', sa.String(), nullable=True),
    sa.Column('parts_count', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['messagebatch.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['importjob.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'phone_number', name='uix_campaign_phone')
    )
    op.create_index(op.f('ix_message_batch_id'), 'message', ['batch_id'], unique=False)
    op.create_index(op.f('ix_message_campaign_id'), 'message', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_message_custom_id'), 'message', ['custom_id'], unique=True)
    op.create_index(op.f('ix_message_gateway_message_id'), 'message', ['gateway_message_id'], unique=False)
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.create_index(op.f('ix_message_import_id'), 'message', ['import_id'], unique=False)
    op.create_index(op.f('ix_message_phone_number'), 'message', ['phone_number'], unique=False)
    op.create_index(op.f('ix_message_scheduled_at'), 'message', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_message_status'), 'message', ['status'], unique=False)
    op.create_index(op.f('ix_message_user_id'), 'message', ['user_id'], unique=False)
    op.create_table('messageevent',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messageevent_event_type'), 'messageevent', ['event_type'], unique=False)
    op.create_index(op.f('ix_messageevent_id'), 'messageevent', ['id'], unique=False)
    op.create_index(op.f('ix_messageevent_message_id'), 'messageevent', ['message_id'], unique=False)
    op.create_table('webhookdelivery',
    sa.Column('webhook_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhookdelivery_event_type'), 'webhookdelivery', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhookdelivery_id'), 'webhookdelivery', ['id'], unique=False)
    op.create_index(op.f('ix_webhookdelivery_message_id'), 'webhookdelivery', ['message_id'], unique=False)
    op.create_index(op.f('ix_webhookdelivery_webhook_id'), 'webhookdelivery', ['webhook_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhookdelivery_webhook_id'), table_name='webhookdelivery')
    op.drop_index(op.f('ix_webhookdelivery_message_id'), table_name='webhookdelivery')
    op.drop_index(op.f('ix_webhookdelivery_id'), table_name='webhookdelivery')
    op.drop_index(op.f('ix_webhookdelivery_event_type'), table_name='webhookdelivery')
    op.drop_table('webhookdelivery')
    op.drop_index(op.f('ix_messageevent_message_id'), table_name='messageevent')
    op.drop_index(op.f('ix_messageevent_id'), table_name='messageevent')
    op.drop_index(op.f('ix_messageevent_event_type'), table_name='messageevent')
    op.drop_table('messageevent')
    op.drop_index(op.f('ix_message_user_id'), table_name='message')
    op.drop_index(op.f('ix_message_status'), table_name='message')
    op.drop_index(op.f('ix_message_scheduled_at'), table_name='message')
    op.drop_index(op.f('ix_message_phone_number'), table_name='message')
    op.drop_index(op.f('ix_message_import_id'), table_name='message')
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_index(op.f('ix_message_gateway_message_id'), table_name='message')
    op.drop_index(op.f('ix_message_custom_id'), table_name='message')
    op.drop_index(op.f('ix_message_campaign_id'), table_name='message')
    op.drop_index(op.f('ix_message_batch_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_contact_phone'), table_name='contact')
    op.drop_index(op.f('ix_contact_import_id'), table_name='contact')
    op.drop_index(op.f('ix_contact_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_campaign_user_id'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_template_id'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_status'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_scheduled_start_at'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_name'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_id'), table_name='campaign')
    op.drop_table('campaign')
    op.drop_index(op.f('ix_webhook_user_id'), table_name='webhook')
    op.drop_index(op.f('ix_webhook_id'), table_name='webhook')
    op.drop_table('webhook')
    op.drop_index(op.f('ix_usermetrics_user_id'), table_name='usermetrics')
    op.drop_index(op.f('ix_usermetrics_id'), table_name='usermetrics')
    op.drop_index(op.f('ix_usermetrics_date'), table_name='usermetrics')
    op.drop_table('usermetrics')
    op.drop_index(op.f('ix_messagetemplate_user_id'), table_name='messagetemplate')
    op.drop_index(op.f('ix_messagetemplate_name'), table_name='messagetemplate')
    op.drop_index(op.f('ix_messagetemplate_id'), table_name='messagetemplate')
    op.drop_table('messagetemplate')
    op.drop_index(op.f('ix_messagebatch_user_id'), table_name='messagebatch')
    op.drop_index(op.f('ix_messagebatch_status'), table_name='messagebatch')
    op.drop_index(op.f('ix_messagebatch_id'), table_name='messagebatch')
    op.drop_table('messagebatch')
    op.drop_index(op.f('ix_importjob_status'), table_name='importjob')
    op.drop_index(op.f('ix_importjob_sha256'), table_name='importjob')
    op.drop_index(op.f('ix_importjob_owner_id'), table_name='importjob')
    op.drop_index(op.f('ix_importjob_id'), table_name='importjob')
    op.drop_table('importjob')
    op.drop_index(op.f('ix_apikey_key'), table_name='apikey')
    op.drop_index(op.f('ix_apikey_id'), table_name='apikey')
    op.drop_table('apikey')
    op.drop_index(op.f('ix_webhookevent_phone_number'), table_name='webhookevent')
    op.drop_index(op.f('ix_webhookevent_message_id'), table_name='webhookevent')
    op.drop_index(op.f('ix_webhookevent_id'), table_name='webhookevent')
    op.drop_index(op.f('ix_webhookevent_gateway_message_id'), table_name='webhookevent')
    op.drop_index(op.f('ix_webhookevent_event_type'), table_name='webhookevent')
    op.drop_table('webhookevent')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
